---
#######################################################################
# General UI/UX
#######################################################################

- name: Set computer name ( as done via System Preferences ->  Sharing )
  command:  scutil --set ComputerName "TrangTran's MD102"
  become: true
  #sudo scutil --set HostName "0x6D746873"
  ##sudo scutil --set LocalHostName "0x6D746873"
  ##sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "0x6D746873"
  

  # Set standby delay to 24 hours (default is 1 hour)
  # sudo pmset -a standbydelay 86400
  

- name: Disable the sound effects on boot
  command: nvram SystemAudioVolume="%01"
  become: true

- name: Disable transparency in the menu bar and elsewhere on Yosemite
  osx_defaults:
    domain: com.apple.universalaccess
    key: reduceTransparency
    type: bool
    value: true


- name: Menu items
  osx_defaults:
    domain: com.apple.systemuiserver
    key: menuExtras
    type: array 
    array_add: true
    value: 
        [
        "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" ,
        "/System/Library/CoreServices/Menu Extras/AirPort.menu" ,
        "/System/Library/CoreServices/Menu Extras/Battery.menu" ,
        "/System/Library/CoreServices/Menu Extras/Clock.menu" 
        ]

- name: Set highlight color to green
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleHighlightColor
    type: string
    value: "0.764700 0.976500 0.568600"

- name: Set sidebar icon size to medium
  osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: 2

- name: Always show scrollbars
  osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowScrollBars
    type: string
    value: "WhenScrolling"
    # Possible values: `WhenScrolling`, `Automatic` and `Always`

# Disable the over-the-top focus ring animation
#defaults write NSGlobalDomain NSUseAnimatedFocusRing -bool false

# Disable smooth scrolling
# (Uncomment if you’re on an older Mac that messes up the animation)
#defaults write NSGlobalDomain NSScrollAnimationEnabled -bool false



- name: Expand save panel by default
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode
    type: bool
    value: true

- name: Expand save panel by default 2
  osx_defaults:
    domain: NSGlobalDomain
    key: NSNavPanelExpandedStateForSaveMode2
    type: bool
    value: true


# Expand print panel by default
#defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
#defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

# Save to disk (not to iCloud) by default
#defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

# Automatically quit printer app once the print jobs complete
#defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable the “Are you sure you want to open this application?” dialog
#defaults write com.apple.LaunchServices LSQuarantine -bool false

# Remove duplicates in the “Open With” menu (also see `lscleanup` alias)
#/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user

# Display ASCII control characters using caret notation in standard text views
# Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
#defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true

# Disable Resume system-wide
#defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

# Disable automatic termination of inactive apps
#defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

# Disable the crash reporter
#defaults write com.apple.CrashReporter DialogType -string "none"

# Set Help Viewer windows to non-floating mode
#defaults write com.apple.helpviewer DevMode -bool true

# Fix for the ancient UTF-8 bug in QuickLook (https://mths.be/bbo)
# Commented out, as this is known to cause problems in various Adobe apps :(
# See https://github.com/mathiasbynens/dotfiles/issues/237
#echo "0x08000100:0" > ~/.CFUserTextEncoding

- name: > 
        Reveal IP address, hostname, OS version, etc. when clicking the clock
        in the login window
  command: defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName
  become: true

# Restart automatically if the computer freezes
#sudo systemsetup -setrestartfreeze on

# Never go into computer sleep mode
#sudo systemsetup -setcomputersleep Off > /dev/null

- name: Disable Notification Center and remove the menu bar icon
  command: launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2>&1 >/dev/null
  ignore_errors: True



# Disable smart quotes as they’re annoying when typing code
#defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
#defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Set a custom wallpaper image. `DefaultDesktop.jpg` is already a symlink, and
# all wallpapers are in `/Library/Desktop Pictures/`. The default is `Wave.jpg`.
#rm -rf ~/Library/Application Support/Dock/desktoppicture.db
#sudo rm -rf /System/Library/CoreServices/DefaultDesktop.jpg
#sudo ln -s /path/to/your/image /System/Library/CoreServices/DefaultDesktop.jpg



#######################################################################
#    Dock
#######################################################################
- name: Set the icon size of Dock items.
  osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 30
  notify:
    - killall Dock

- name: Automatically hide and show the Dock.
  osx_defaults:
    domain: com.apple.dock
    key: autohide
    type: bool
    value: true
  notify:
    - killall Dock

- name: Remove the autohide delay.
  osx_defaults:
    domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
  notify:
    - killall Dock

- name: Change minimze/maximize window effect
  osx_defaults:
    domain: com.apple.dock
    key: mineffect
    type: string
    value: "scale"

- name: Minimize windows into their application's icon
  osx_defaults:
       domain: com.apple.dock
       key: minimize-to-application
       type: bool
       value: true

- name: Enable spring loading for all Dock items
  osx_defaults:
       domain: com.apple.dock
       key: enable-spring-load-actions-on-all-items
       type: bool
       value: true
#######################################################################
#   Finder
#######################################################################
- name: Allow quitting via ⌘ + Q; doing so will also hide desktop icons
  osx_defaults:
      domain: com.apple.finder
      key: QuitMenuItem 
      type: bool
      value: true

- name: Show icons for hard drives on the desktop 
  osx_defaults:
      domain: com.apple.finder
      key: ShowHardDrivesOnDesktop
      type: bool
      value: true

- name: Show icons for external hard drives on the desktop 
  osx_defaults:
      domain: com.apple.finder
      key: ShowExternalHardDrivesOnDesktop
      type: bool
      value: true

- name: Show icons for servers on the desktop 
  osx_defaults:
      domain: com.apple.finder
      key: ShowMountedServersOnDesktop
      type: bool
      value: true

- name: Show icons for removable media on the desktop 
  osx_defaults:
      domain: com.apple.finder
      key: ShowRemovableMediaOnDesktop
      type: bool
      value: true

- name: Show hidden files by default
  osx_defaults:
      domain: com.apple.finder
      key: AppleShowAllFiles
      type: bool
      value: true

- name: Show all filename extensions
  osx_defaults:
      domain: NSGlobalDomain 
      key: AppleShowAllExtensions
      type: bool
      value: true

- name: Show status bar
  osx_defaults:
      domain: com.apple.finder
      key: ShowStatusBar
      type: bool
      value: true

- name: Show path bar
  osx_defaults:
      domain: com.apple.finder
      key: ShowPathBar
      type: bool
      value: true

- name: Display full POSIX path as Finder window title
  osx_defaults:
      domain: com.apple.finder
      key: _FXShowPosixPathInTitle
      type: bool
      value: true

- name: Keep folders on top when sorting by name
  osx_defaults:
      domain: com.apple.finder
      key: _FXSortFoldersFirst
      type: bool
      value: true

- name: When performing a search, search the current folder by default
  osx_defaults:
      domain: com.apple.finder
      key: FXDefaultSearchScope
      type: string
      value: "SCcf"

- name: Disable the warning when changing a file extension
  osx_defaults:
      domain: com.apple.finder
      key: FXEnableExtensionChangeWarning
      type: bool
      value: false

- name: Enable spring loading for directories
  osx_defaults:
      domain: NSGlobalDomain
      key: com.apple.springing.enabled
      type: bool
      value: true

- name: Remove the spring loading delay for directories
  osx_defaults:
      domain: NSGlobalDomain 
      key: com.apple.sprining.enabled
      type: bool
      value: true


- name: Show item info near icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c "{{ item }}"  ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "Set :DesktopViewSettings:IconViewSettings:showItemInfo true"
    - "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" 
    - "Set :StandardViewSettings:IconViewSettings:showItemInfo true"

- name: Show item info to the right of the icons on the desktop
  shell: /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
    - "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" 
    - "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid"
    - "Set :StandardViewSettings:IconViewSettings:arrangeBy grid"

- name: Increase grid spacing for icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
      - "Set :DesktopViewSettings:IconViewSettings:gridSpacing 100" 
      - "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 100"
      - "Set :StandardViewSettings:IconViewSettings:gridSpacing 100"

- name: Increase the size of icons on the desktop and in other icon views
  shell: /usr/libexec/PlistBuddy -c "{{ item }}" ~/Library/Preferences/com.apple.finder.plist
  with_items:
      - "Set :DesktopViewSettings:IconViewSettings:iconSize 80" 
      - "Set :FK_StandardViewSettings:IconViewSettings:iconSize 80"
      - "Set :StandardViewSettings:IconViewSettings:iconSize 80"

- name: Use list view in all Finder windows by default
  #Four-letter codes for other view modes: 'icnv', 'clmv', 'Flwv'
  osx_defaults:
      domain: com.apple.finder
      key: FXPreferredViewStyle
      type: string
      value: "Nlsv"


- name: Disable the warning before emptying the Trash
  osx_defaults:
      domain: com.apple.finder
      key: WarnOnEmptyTrash
      type: bool
      value: false

- name: Enable AirDrop over Ethernet and on unsupported Macs running Lion
  osx_defaults:
      domain: com.apple.NetworkBrowser
      key: BrowseAllInterfaces
      type: bool
      value: true

- name: Show the ~/Library folder
  shell: chflags nohidden ~/Library

- name: Show the /Volumes folder
  shell: sudo chflags nohidden /Volumes

- name: Expand General, OpenWith, Privileges
  command: >
        defaults write com.apple.finder FXInfoPanesExpanded -dict 
            General -bool true 
            OpenWith -bool true 
            Privileges -bool true



###############################################################################
# Terminal & iTerm 2                                                          #
###############################################################################

#defaults write com.apple.terminal StringEncodings -array 4
- name : Only use UTF-8 in Terminal.app
  osx_defaults:
    domain: com.apple.terminal
    key: StringEncodings
    type: array
    value: 4

- name: copy init folder
  copy: src=init dest={{ansible_env.HOME}}/ force=yes

- name: Use a modified version of the Solarized Dark theme by default in Terminal.app
  shell: osascript "{{ ansible_env.HOME }}"/init/SolarizedDarkTheme.scpt

# Enable “focus follows mouse” for Terminal.app and all X11 apps
# i.e. hover over a window and start typing in it without clicking first
#defaults write com.apple.terminal FocusFollowsMouse -bool true
#defaults write org.x.X11 wm_ffm -bool true

# Enable Secure Keyboard Entry in Terminal.app
# See: https://security.stackexchange.com/a/47786/8918
#defaults write com.apple.terminal SecureKeyboardEntry -bool true

# Disable the annoying line marks
#defaults write com.apple.Terminal ShowLineMarks -int 0
#
- name: Install Powerline Fonts
  copy: src=fonts/ dest={{ansible_env.HOME}}/Library/Fonts/

- name: Install the customized theme for iTerm
  shell: open "${HOME}/init/iTerm2.itermcolors"

# Don’t display the annoying prompt when quitting iTerm
#defaults write com.googlecode.iterm2 PromptOnQuit -bool false


