---
# tasks file for test_role
    #- name : Print something
      #command: echo "This is test_role"

    #- name : Test variables
      #command: echo "Testing variable {{ item }}"
      #with_items: "{{ members  }}"

    #- name : get installed apps
      #command : /usr/local/bin/brew cask list
      #register : installed_apps

    #- name : not installed app
      #command: echo "{{ item }} not installed"
      #with_items:
          #"{{ members }}"
      #when :
          #"'{{ item }}' not in installed_apps.stdout "

    #- name: create directory
      #file: path={{ansible_env.HOME}}/.init state=directory

    #- name: copy folder
      #copy: src=init dest={{ansible_env.HOME}}/.init directory_mode=yes

